#!/usr/bin/env python3

from os import chdir, getcwd as pwd, popen as getOutputOf, system as run
from os.path import join as joinPath
from shutil import copyfile
from colorama import init as colorama_init, Fore

def main():
    colorama_init()
    print("      ", Fore.RED, "GitHub CodeSpace Toolkit", Fore.RESET)
    print("      ", Fore.RED, "version 1.1", Fore.RESET)
    print("      ", Fore.GREEN, "Install in Progress", Fore.RESET)

    ## output supression start
    # get current directory
    currentDirectory = pwd()
    # get main directory
    mainDirectory = joinPath(currentDirectory, "main")
    # go to main directory
    chdir(mainDirectory)
    # get filenames
    filenames = getOutputOf("ls").read().readLines().replace("\n", "")
    # run files that need running
    

if __name__=="__main__":main()