#!/usr/bin/python

from sys import argv as args
from os import chdir, getcwd as pwd, system as run
from os.path import expanduser, join as joinPath
import subprocess

def main():
    currentDirectory = pwd()
    homeDirectory = expanduser("~")

    # change to home directory and clone custombasher repo
    chdir(homeDirectory)
    run("git clone https://github.com/d33pster/custombash.git 2> /dev/null")

    # get custombash directory and change to custombash directory
    cbDirectory = joinPath(currentDirectory, "custombash")
    chdir(cbDirectory)

    # run setup-gct (customised just for this project)
    subprocess.Popen([f"{joinPath(cbDirectory, 'setup-gct')}", f"{args[1]}"]).wait()

    # delete custombash directory
    chdir(homeDirectory)
    run("rm -rf custombash")
    
    # change back to the original directory
    chdir(currentDirectory)

if __name__ == "__main__":
    main()