#!/usr/bin/env python3

from os import system as run
from sys import argv as args, exit as escape
from colorama import init as colorama_init, Fore

def main():
    colorama_init()
    # get version
    with open("gct-version", "r") as vers:
        version = vers.read().replace("\n","")
    # setting check params
    commit_message = ""
    filename = ""

    try:
        args[2]
    except IndexError:
        # this means only args[1] might be present
        try:
            args[1]
        except IndexError:
            # this means no args are provided
            print(Fore.RED, "ERROR:", Fore.RESET, " No filename/commit-message provided.")
            escape()
    
    # assign values
    if len(args)>2:
        filename = args[1]
        commit_message = args[2]

        run(f"git add {filename}")
    else:
        commit_message = args[1]
        
        run("git add *")
    
    run(f"git commit -m {commit_message}")
    run("git push")

if __name__ == "__main__":main()